In [2]:
import numpy as np
from numpy import linalg as la
from numpy.linalg import inv, solve

In [5]:
x = np.matrix([[-2, 0, 0], [0, 1, 0], [0, 0, 1]])

def svd(x):
    m = x.shape[0] #number of rows
    n = x.shape[1] #number of columns
    
    x_t = x.transpose()
    xt_x = np.matmul(x_t, x)

    w, v = la.eig(xt_x)
    
    w = np.sort(w)[::-1]
    d = np.zeros((m, n))
    np.fill_diagonal(d, w)
    
    v_t = v.transpose()
    
    d_inv = inv(d)
    u = np.matmul(x, np.matmul(v, d_inv))
    
    return u, d, v_t
    
u, d, v_t = svd(x)
print('Original Matrix:\n', x)
print('\nA = U*S*V_t:\n', np.matrix.round(np.matmul(u, np.matmul(d, v_t))))
print('Matrix U:\n', u)
print('Matrix S:\n', d)
print('Matrix V transpose:\n', v_t)

Original Matrix:
 [[-2  0  0]
 [ 0  1  0]
 [ 0  0  1]]

A = U*S*V_t:
 [[-2.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
Matrix U:
 [[-0.5  0.   0. ]
 [ 0.   1.   0. ]
 [ 0.   0.   1. ]]
Matrix S:
 [[4. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matrix V transpose:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
